# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: robert.sh
email: bob.m.shannon@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site is a collection of blog posts about problems featuring topics of personal
  interest and technical problems that I've ran into.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://robert.sh" # the base hostname & protocol for your site
twitter_username: bobmshannon
github_username:  bobmshannon
permalink: "/blog/:title"
full_name: "Robert Shannon"

# Build settings
markdown: kramdown
